#!/usr/bin/env python3
"""
png2c.py — convert a PNG into a C header for the stitch-counter project.

Generates an RGB565 sprite array with a transparent color key (pure green,
0x07E0). Fully-transparent pixels in the source PNG are mapped to the key;
all other pixels are quantized to RGB565.

Usage:
    python3 tools/png2c.py path/to/yarn.png            # writes yarn.h next to it
    python3 tools/png2c.py path/to/yarn.png --name YARN --out icons/yarn.h
    python3 tools/png2c.py path/to/yarn.png --scale 2  # nearest-neighbor upscale

The output header defines:
    static const uint16_t <NAME>[<W>*<H>] = { ... };
    #define <NAME>_W <W>
    #define <NAME>_H <H>

Requires: Pillow  (pip install pillow)
"""

import argparse
import os
import sys

try:
    from PIL import Image
except ImportError:
    print("error: Pillow not installed. Run: pip install pillow", file=sys.stderr)
    sys.exit(1)

KEY_RGB = (0x00, 0xFF, 0x00)   # bright green sentinel — alpha=0 maps here

def rgb_to_565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)

def png_to_pixels(path, scale):
    im = Image.open(path).convert("RGBA")
    if scale != 1:
        im = im.resize((im.width * scale, im.height * scale), Image.NEAREST)
    out = []
    for y in range(im.height):
        for x in range(im.width):
            r, g, b, a = im.getpixel((x, y))
            if a < 128:
                r, g, b = KEY_RGB
            elif (r, g, b) == KEY_RGB:
                # Avoid accidentally matching the key
                g = 0xFE
            out.append(rgb_to_565(r, g, b))
    return im.width, im.height, out

def format_array(pixels, width, indent="    "):
    lines = []
    for row_start in range(0, len(pixels), width):
        row = pixels[row_start:row_start + width]
        body = ", ".join(f"0x{p:04X}" for p in row)
        lines.append(indent + body + ",")
    return "\n".join(lines)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("png", help="input PNG file")
    ap.add_argument("--name", help="symbol name (default: uppercased filename)")
    ap.add_argument("--out",  help="output .h path (default: alongside PNG)")
    ap.add_argument("--scale", type=int, default=1, help="nearest-neighbor scale")
    args = ap.parse_args()

    base = os.path.splitext(os.path.basename(args.png))[0]
    name = (args.name or "ICON_" + base.upper()).replace("-", "_")
    out_path = args.out or os.path.join(os.path.dirname(args.png), base + ".h")

    w, h, pixels = png_to_pixels(args.png, args.scale)

    guard = name + "_H_"
    header = f"""// Generated by tools/png2c.py from {os.path.basename(args.png)}
// {w}x{h} RGB565 sprite. Transparent color key = 0x07E0 (pure green).

#ifndef {guard}
#define {guard}

#include <stdint.h>

#define {name}_W {w}
#define {name}_H {h}

static const uint16_t {name}[{w}*{h}] = {{
{format_array(pixels, w)}
}};

#endif
"""

    with open(out_path, "w") as f:
        f.write(header)

    print(f"wrote {out_path}  ({w}x{h}, {len(pixels)} px, {len(pixels)*2} bytes)")

if __name__ == "__main__":
    main()
